name: 'Excellence In Action!'
favicon: null
layout_spectrum: 0.24978
typography_spectrum: 0.8870206463616341
title: 'Excellence in Action!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0043fa'
    - '#ad9741'
    - '#cedbfe'
    - '#6b92fc'
  brandStrength: 0.5451755146495998
  lightness: 0.6875
  saturation: 0.6710572901647538
  rhythmicContrast: 0.25
purpose: []
